### ISSUE TITLE
Does this plugin support the WooCommerce Subscriptions plugin?

### ISSUE THREAD

**Issue by paulgambill** [coinbase/coinbase-woocommerce#10]
I'd like to use this plugin with my store at [The Happy Crate](https://thehappycrate.com) but I need it to work with the [WooCommerce Subscriptions](http://www.woothemes.com/products/woocommerce-subscriptions/) plugin. Does this integrate with that? And if not, consider it a feature request please.

**Comment by denzel100** [comment]
+1

https://developers.coinbase.com/docs/merchants/recurring-payments

**Comment by DeysonOrtiz** [comment]
I would love to see this added a feature as well. :)

**Comment by renatonascalves** [comment]
Folks, I'm considering if people are actually needing this feature... So far I was able to find only one person asking... :/

**Comment by dcr207** [comment]
I'd love to have this feature available as well!

**Comment by PorridgeFactory** [comment]
I'd love it if this was created too.  I would implement it right away.
That and using coinbase with multiple currencies.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
