### ISSUE TITLE
Payment expiration issue

### ISSUE THREAD

**Issue by Speran49** [coinbase/coinbase-woocommerce#12]
Hi,

I am using this plugin for subscriptions on my site (Praying you will integrate auto renewals in the near future because this is becoming a nightmare)...

Anyway, I have users now renewing for the first time, but I am running into multiple problems.
1. First issue involves a user going to pay and then waiting too long to pay. He then went to refresh and pay again and received the following error "Invalid Payment Method". Do you know why this is occurring?
2. Second issue involves a user hitting cancel when the link is about to expire in order to refresh, yet his order is then marked as failed and he is unable to new renew? Why would it expire his entire order? How can I guarantee he still has a subscription and can renew if payment is cancelled out and he is no longer able to renew now?

Thank you,

Julian

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
