### ISSUE TITLE
Look into new woocommerce payment refund functionality

### ISSUE THREAD

**Issue by dominic-p** [coinbase/coinbase-woocommerce#13]
You might also want to look into the new payment refund functionality introduced in WC 2.2.

**Comment by aianus** [comment]
v2.1.2 fixes the undefined method problem. Leaving the issue open in regards to your second suggestion.

**Comment by aianus** [comment]
I looked into this today and unfortunately the way WooCommerce has implemented the refund feature, it assumes the gateway supports partial refunds (https://docs.woothemes.com/wc-apidocs/source-class-WC_Payment_Gateway.html#234-247).

We do not support partial refunds via the orders API so we can't support the automated payment refund functionality (unless the gateway API key is authorized for unrestricted debits on the account, which is not something we want to encourage).

**Comment by dominic-p** [comment]
Thanks for looking into that. Maybe it would be worth opening an issue on the WooCommerce repo to see what the devs think about allowing gateways to support full refunds only?
