### ISSUE TITLE
PHP Fatal Error in Coinbase

### ISSUE THREAD

**Issue by bentasm1** [coinbase/coinbase-woocommerce#17]
Any time Coinbase initiates a callback, this error is generated in error_log.  WordPress 4.0, WooCommerce 2.2.X.

Regards,

Ben

[01-Oct-2014 23:19:11 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Coinbase: callback for non-pending order 6650' in /home/XXXXXX/public_html/wp-content/plugins/coinbase-woocommerce-master/callback.php:59
Stack trace:
#0 [internal function]: coinbase_callback('')
#1 /home/pooalexa/public_html/wp-includes/plugin.php(505): call_user_func_array('coinbase_callba...', Array)
#2 /home/pooalexa/public_html/wp-settings.php(353): do_action('init')
#3 /home/pooalexa/public_html/wp-config.php(96): require_once('/home/XXXXXX/...')
#4 /home/pooalexa/public_html/wp-load.php(29): require_once('/home/XXXXXX/...')
#5 /home/pooalexa/public_html/wp-blog-header.php(12): require_once('/home/XXXXXX/...')
#6 /home/pooalexa/public_html/index.php(17): require('/home/XXXXXX/...')
#7 {main}
  thrown in /home/XXXXXX/public_html/wp-content/plugins/coinbase-woocommerce-master/callback.php on line 59

**Comment by aianus** [comment]
Sounds like the checkout was generated without setting the order to 'Payment Pending' for some reason. If you set the order status to 'Payment Pending' it should clear up this issue for this order. Other orders should not be affected.

**Comment by bentasm1** [comment]
Thanks for replying, one year and six days later.  Of course, your reply was meaningless because this was not a problem on a single order, but on all of them.

However, none of that matters, as we switched to CoinPayments.net, as your service, staff, and attitude and lack of creating a proper payment gateway and supporting it, blows donkey nuts.

Cheers

**Comment by bentasm1** [comment]
PS -- A.I. Anus.  Named appropriately.
