### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by neodo** [coinbase/coinbase-woocommerce#20]
Please update the plugin, it isn't working anymore with new woocommerce update.
Thank you

**Comment by aianus** [comment]
Try the latest version, v2.1.2

Let me know if you run into any more difficulties

**Comment by zjwhitehead** [comment]
Im having errors with this plugin. Im on the latest WooCommerce (2.4.7) and Wordpress. It says there was an error processing your request. It doesnt lead to another page or anything

**Comment by aianus** [comment]
The order notes on the order should have more information on why the request failed.

Try double-checking your API keys and making sure your merchant profile on Coinbase is filled out (tax identifier, etc.)
