### ISSUE TITLE
Error when checking out

### ISSUE THREAD

**Issue by chrizinho** [coinbase/coinbase-woocommerce#22]
Hello, 

I'm getting the following error after clicking "Proceed to Coinbase" at my check out screen. 
I'm puzzled as to what it means... Any ideas?

Fatal error: Call to undefined method WooCommerce::add_error() in /home1/name/public_html/mydomain.com/wp-content/plugins/coinbase-woocommerce-master/coinbase-woocommerce.php on line 216

**Comment by aianus** [comment]
This is fixed in v2.1.2
