### ISSUE TITLE
Sorry, but there was an error processing your order. Please try again or try a different payment method.

### ISSUE THREAD

**Issue by buyacsgo** [coinbase/coinbase-woocommerce#28]
I have used plugin https://wordpress.org/plugins/coinbase-woocommerce/

WordPress version: 4.5

Website: https://buyacsgo.com/

In woocommerce -> settings Coinbase Payment Gateway
status: Successfully connected Coinbase account 'soviksaha2013@gmail.com'

But in checkout page it says - Sorry, but there was an error processing your order. Please try again or try a different payment method.

**Comment by aianus** [comment]
What permissions do you have set on the API Key?

**Comment by buyacsgo** [comment]
API V2

**Comment by aianus** [comment]
Uncheck all of the API V2 permissions and enable the 'user' and 'merchant' permissions from API v1. That should fix your problem.

**Comment by buyacsgo** [comment]
Okay let me check. Any latest plugin for wordpress ?

**Comment by buyacsgo** [comment]
Still showing same error. Try to checkout via Coinbase.

https://buyacsgo.com

**Comment by aianus** [comment]
Can you check the order notes in the woocommerce admin site?

There should be a note with more details starting with "Error while processing coinbase payment:"

**Comment by aianus** [comment]
Also, have you filled out your merchant profile (including tax identifier) over at https://www.coinbase.com/merchant_profiles?

This is a required step.

**Comment by buyacsgo** [comment]
Merchant Tax ID Type
Merchant Tax ID

what to do here ?

**Comment by aianus** [comment]
Enter the tax identifier information for your company (this would be your SSN or EIN in the United States)

**Comment by buyacsgo** [comment]
can you please contact me via Skype or FB ??

**Comment by aianus** [comment]
That's not my job, sorry.

If you email support@coinbase.com they can help you with this sort of non-technical issue.
