### ISSUE TITLE
Add support for coinbase Ethereum payments :) Pretty please?

### ISSUE THREAD

**Issue by melt7777** [coinbase/coinbase-woocommerce#33]
coinbase supports eth payment, can we get that support for this plugin? Thank you!!!

**Comment by melt7777** [comment]
Especially now that BTC is slower to confirm, ETH would be a great way to offer more coins and increase use of crypto coins for transacting!

**Comment by melt7777** [comment]
And also because it's an important feature of your product that deserves attention. Thanks!

**Comment by svpn** [comment]
Seems they abandoned this plugin.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
