### ISSUE TITLE
Woocommerce 3.0 API V2 & Oauth 

### ISSUE THREAD

**Issue by odapplications** [coinbase/coinbase-woocommerce#35]
Hey I was wondering if you had any plans to upgrade your plugin..

I love the idea behind it and installed it on my site.. however it returns an error when someone tries to checkout on coinbase. 

I have enabled the api v1 for user and merchant. also added the api keys and it verified my connection.
I get the following error upon checkout - Sorry, but there was an error processing your order. Please try again or try a different payment method.

I was wondering if this was because of the outdated api or because of woocommerce 3.0

Thanks for the release in anycase!

**Comment by nocean** [comment]
@odapplications I see you never received a response, so am guessing this plugin might be abandoned. Did you come up with a solution?

**Comment by odapplications** [comment]
Use coingate

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
