### ISSUE TITLE
Getting error: Could not validate API Key: Status code 401 with WP 4.9 and woo-commerce Version 3.2.5 

### ISSUE THREAD

**Issue by Softeezy** [coinbase/coinbase-woocommerce#38]
Hi, 
I am getting the error Could not validate API Key: Status code 401 on the woocommerce>checkout>coinbase page but I have put the API key and API secret from coinbase and getting the error in Wordpress Version 4.9 and woo-commerce Version 3.2.5. 

Also when clicking on the proceed to coinbase on the checkout page this error shows "Sorry, but there was an error processing your order. Please try again or try a different payment method."

Can you please help me regard it?

Regards
Tanveer

**Comment by stefanbaranowski** [comment]
Hey Tanveer,

By any chance did you ever get this resolved? I have the same error on my store, yet I have enabled new API keys but still seeing the error message. 

Thanks,
Stefan

**Comment by interwerk** [comment]
Same Problem! ... No help?

**Comment by Softeezy** [comment]
Actually, I have found another plugin which helps me to integrate Coinbase and other altcoins perfectly. (GoUrl Woocommerce) Still using it and it's easy and helpful. I hope this will helps you out.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
