### ISSUE TITLE
Not compartible with the latest version of Wordpress

### ISSUE THREAD

**Issue by mcperfect** [coinbase/coinbase-woocommerce#39]
This Plugin does not have an documentation and it is not working with the current version of WordPress (version 4.9xx).
All get is a server error message. Please fix this error

**Comment by waynep16** [comment]
will this ever be updated or integrated in to coinbase commerce !?

**Comment by uxcode1** [comment]
@waynep16 Check [this](https://github.com/infinue/woocommerce-gateway-coinbase-commerce) out. A Coinbase Commerce extension for WooCommerce.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
