### ISSUE TITLE
BTC as default currency

### ISSUE THREAD

**Issue by jeffa105** [coinbase/coinbase-woocommerce#7]
Hi,

This isn't so much an issue as it is a feature request, hope that's ok :)

Would it be possible to incorporate BTC as an optional default currency in WooCommerce, so that prices display in BTC as opposed to USD, etc.?

Thanks so much for your work on this, the plugin is fantastic!

Jeff
Bitcoinwine.com

**Comment by aianus** [comment]
Great idea, this will be implemented in v3.0.0 of the plugin (#24)
